### PR TITLE
Implement ConcurrentEffect[TraceIO[F, ?]]

### PR DESCRIPTION
**Pull request by sbuzzard**
Note that though I based this PR  off series/1.2.x, I'm guessing we'll need at least a series/1.3.x for this change.  I realized I needed it for work change (for start / join functionality) - worked around it but would like to get the non-hacky version in at some point ...

### CODE REVIEW

**Comment by sbuzzard** [comment]
bah, this isn't a fix either - it causes the root trace span to be emitted every time.  So I'm closing until I have a fix that actually works.

**Comment by sbuzzard** [comment]
actually this does work using tie - I had tried a work-around with a typeclass instance in my local build but was using trace rather than tie since tie is package private.

**Comment by mpilquist** [comment]
Do you think we should provide a `Timer[TraceIO]` that's derived from `Timer[IO]`?

**Comment by sbuzzard** [comment]
yeah, I think that makes sense.  I'll create a follow-on PR for that tonight.

**Pull request merged**
