### PR TITLE
include a poly identity function to the TraceT implicit scope - usefu…

### PR DESCRIPTION
**Pull request by sbuzzard**
…l for building enhanced functionality on top of TraceT (such as an EitherTBuilder to make working with the EitherT monad transformer with TraceT and  derived data types).

### CODE REVIEW

**Comment by mpilquist** [comment]
Oh interesting, I think we should make `fs2.util.UF1.id` an implicit def instead of a regular def.

**Comment by sbuzzard** [comment]
Don't know why I glossed over ID - should have just delegated to that here.   I'm wondering if it's made implicit if we'd still need this (since we're partially applying the type in the case of TraceT) ...

**Comment by sbuzzard** [comment]
It works fine.  So I'm going to close this assuming we make id implicit in fs2, okay (I'll add a temporary implicit val traceTaskPolyId = UF1.id[TraceTask] for what I'm doing until it's available in fs2 in a release).

**Comment by mpilquist** [comment]
👍 Cool

**Pull request closed without merging**
